stages:
  - build
  - test
  - publish

compile scala sources:
  stage: build
  tags:
    - aws
  script:
    - sbt test:compile

sbt test:
  stage: test
  tags:
    - aws
  script:
    - sbt coverage test coverageReport

publish on bintray:
  stage: publish
  # TODO Add `only: master` once the process succeed
  when: manual
  tags:
    - aws
  script:
    - sbt -Dbintray.user=gitlab-ci -Dbintray.pass=$BINTRAY_API_KEY publish

image: colisweb/scala-sbt-gke:adoptjdk11-1.2.8-8.11.3-9.2.7.0
variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
  COURSIER_CACHE: "sbt-cache/coursier"
cache:
  key: "sbt-$CI_BUILD_REF_NAME"
  paths:
    - sbt-cache

before_script:
- gpg --import  <(echo "$GITLAB_PGP_PRIVATE_KEY")
- git secret reveal
- source secrets-env.sh