stages:
  - build
  - test
  - publish

compile scala sources:
  stage: build
  script:
    - sbt test:compile

sbt test:
  stage: test
  script:
    - sbt coverage test coverageReport

publish on bintray:
  stage: publish
  only:
    - master
    - sbt-release
  variables:
    GIT_STRATEGY: clone
  script:
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name "$GITLAB_USER_NAME"
    - git fetch
    - git checkout develop
    - git checkout $CI_COMMIT_REF_NAME 
    - git remote set-url origin https://gitlab.ci1:$GIT_CI_PASS@gitlab.com/$CI_PROJECT_PATH.git
    - sbt -Dbintray.user=gitlab-ci -Dbintray.pass=$BINTRAY_PASS "release skip-tests with-defaults"
    - git rebase $CI_COMMIT_REF_NAME develop
    - git push origin develop --force-with-lease

image: hseeberger/scala-sbt:11.0.3_1.2.8_2.12.8
variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
  COURSIER_CACHE: "sbt-cache/coursier"
cache:
  key: "sbt-$CI_BUILD_REF_NAME"
  paths:
    - sbt-cache

before_script:
  - gpg --import  <(echo "$GITLAB_PGP_PRIVATE_KEY")
  - source <(gpg -q --decrypt secrets-env.sh.secret)
