include:
  - 'https://colisweb-open-source.gitlab.io/ci-common/templates/scala.yml'

format:
  extends: .sbt-format
  tags: []

test skills:
  extends: .sbt-test
  tags: []

unused-dependencies:
  extends: .sbt-unused-dependencies
  tags: []

version:
  extends: .version
  tags: []

publish on sonatype:
  extends: .sonatype-publish
  tags: []

